### ISSUE TITLE
[FR] Support for Craft Commerce products? Categories?

### ISSUE THREAD

**Issue by frontedbe** [internetztube/craft-slug-equals-title#11]
This feature for Craft Commerce products, Categories, etc would be great! Would this be hard to implement? A client of mine would find this very handy!

**Comment by internetztube** [comment]
What other content types would you need this for?

**Comment by frontedbe** [comment]
Craft Commerce Products would suffice!

**Comment by internetztube** [comment]
Thanks for your feature request.
https://github.com/internetztube/craft-slug-equals-title/releases/tag/1.3.0

```
composer update internetztube/craft-slug-equals-title
```
