### ISSUE TITLE
Only load asset bundle on required controllers/actions

### ISSUE THREAD

**Issue by nfourtythree** [internetztube/craft-slug-equals-title#12]
At the moment the asset bundle is being loaded on every control panel request (https://github.com/internetztube/craft-slug-equals-title/blob/master/src/SlugEqualsTitle.php#L31). This is not a good practice as it could cause issues/conflicts with other plugins/assets.

One such issue is in Commerce with the email preview feature: https://github.com/craftcms/commerce/issues/1950

The asset bundle should only be registered/loaded when it is absolutely required.

Either the logic will need updating in the `init()` method to selectively register the bundle or you could use template hooks for the pages that need the bundle and register them that way.

e.g. `{% do view.registerAssetBundle("mynamespace\\FooBundle") %}`

**Comment by internetztube** [comment]
Thanks for the report! Will provide a fix later today.

**Comment by internetztube** [comment]
The bug should be fixed with 1.3.1. @mdominguez 
```
composer update internetztube/craft-slug-equals-title
```
