### ISSUE TITLE
Slugs with accented characters

### ISSUE THREAD

**Issue by zehfred** [internetztube/craft-slug-equals-title#13]
Not sure if this is an issue or a feature request. The plugin is awesome but when the title has accented characters like à ó ç, etc, the slug keeps them. Would it be possible to convert those characters?

For example, imagine I have a title like "Baloiço José Gomes". The slug becomes "baloiço-josé-gomes". How could it become "baloico-jose-gomes"? Is there some kind of filter?

**Comment by internetztube** [comment]
I guess you're looking for this setting. 
https://docs.craftcms.com/api/v3/craft-config-generalconfig.html#limitautoslugstoascii
https://github.com/internetztube/craft-slug-equals-title/issues/8

**Comment by zehfred** [comment]
That’s what I wanted! Thank you so much :))

**Comment by internetztube** [comment]
Cool!
