### ISSUE TITLE
Titles that contain a / (slash) generate an error

### ISSUE THREAD

**Issue by arifje** [internetztube/craft-slug-equals-title#15]
When the plugin is enabled, an error will be generated when you have a / (slash) in the title on saving. The entry is created, but not editable due to a wrongly formatted URL.

This:

![Screenshot 2021-11-23 at 19 50 49](https://user-images.githubusercontent.com/1286410/143194947-52988470-21e4-4a92-980d-c0c325cebd52.png)

Will result in this:

![Screenshot 2021-11-23 at 19 51 07](https://user-images.githubusercontent.com/1286410/143195185-90a824ad-046a-4364-9a24-dcbfe24974ab.png)

When I disable the switch before I save the entry, it all works fine.

Using the most recent version.

**Comment by internetztube** [comment]
Thanks for the bug report. Should be fixed with 1.3.4.
