### ISSUE TITLE
Dots in title?

### ISSUE THREAD

**Issue by gixxy22** [internetztube/craft-slug-equals-title#16]
Is there a config file or anything to allow/disallow certain characters.

I would like to keep the dots/periods in the slug but its removing them, and Craft replaces them with hyphens.

**Comment by internetztube** [comment]
It looks like this setting is hard coded. Unfortunately, I can't do much in the plugin either.
https://github.com/craftcms/cms/blob/develop/src/helpers/ElementHelper.php#L74
