### ISSUE TITLE
Error with the resave/entries command line

### ISSUE THREAD

**Issue by elodiegrondin** [internetztube/craft-slug-equals-title#3]
## ISSUE
Thank you for this useful plugin !
Unfortunately, I get an error when I run the command ./craft resave/entries

## ERROR
Resaving {EntryTitle} ({entryId}) ... error: Calling unknown method: craft\console\Request::getBodyParam()

It would be great if you could solve this problem !

**Comment by internetztube** [comment]
Thanks for a bug report!

**Comment by internetztube** [comment]
Thanks for the bug report!
https://github.com/internetztube/craft-slug-equals-title/releases/tag/1.1.4
