### ISSUE TITLE
Nothing changes on the slug field on the sections we picked?

### ISSUE THREAD

**Issue by green17** [internetztube/craft-slug-equals-title#4]
Hi installed this and see the CP to pick sections but nothing changes on the slug field on the sections we picked?

Craft CMS v 3.4.29.1

**Comment by internetztube** [comment]
Thanks for your bug report!

The bug should be fixed with 1.1.5. 
```
composer update internetztube/craft-slug-equals-title
```

**Comment by green17** [comment]
@internetztube that's now working perfectly thanks so much. :-)
