### ISSUE TITLE
Add support for limitAutoSlugsToAscii config setting

### ISSUE THREAD

**Issue by TomDeSmet** [internetztube/craft-slug-equals-title#8]
It seems this plugin doesn't take into account the general `limitAutoSlugsToAscii` [config setting](https://docs.craftcms.com/api/v3/craft-config-generalconfig.html#limitautoslugstoascii).

It would be nice if it did that.

**Comment by internetztube** [comment]
Thanks for your feature request!
```
composer update internetztube/craft-slug-equals-title
```
